### ISSUE TITLE
Xclaim

### ISSUE THREAD

**Issue by Th3v0x** [mertout/XClaim#2]
Good I wanted to comment something about the function of "look at pieces" that shows the border of your protection with worldborder and that generates that the users that are outside the border receive damage and if you enter the protection in which they are showing the border you will be locked inside until the border stops showing (the border would be good to be shown with particles and not with worldborder).
I also recommend that you add a claim removal confirmation function to avoid problems with users.
The user who has permissions on the claim should be able to renew it without having to rely on the owner.
Thanks for reading and taking me into account.
I love the plugin

**Comment by mertout** [comment]
Thanks for suggesting it can!
